nationalarchives/dr2-ingest

- ingest-upsert-archive-folders/README.md
- ingest-upsert-archive-folders/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/testUtils/ExternalServicesTestUtils.scala
Instead, it will just post that a title/description has changed
> Stop showing changed titles and descriptions in Slack

- ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/FileProcessor.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/FileProcessorTest.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/LambdaTest.scala
We're expecting this to be an integer in Dynamo but it's a string in the
Bagit json. This should write it to the bagit file as a number so it
should end up in Dynamo as a number.
> Write the suffix as an integer.

- ingest-asset-reconciler/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/LambdaTest.scala
'assetName' is not needed for SNS message but it is needed for the next step in step function, therefore, it makes more sense to put it in the main output.
In the SNS message, assetId was replaced with assetName but we actually need it for the message
> Move assetName out of SNS message and into main output & reaplace with assetId

- get-latest-preservica-version-lambda/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- get-latest-preservica-version-lambda/src/test/scala/uk/gov/nationalarchives/testUtils/ExternalServicesTestUtils.scala
The endpoint is /entity/entities/by-identifier. We were only calling
/entity/by-identifier.
> Correct the by-identifier endpoint.

- ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-asset-reconciler/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/LambdaTest.scala
- ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/testUtils/ExternalServicesTestUtils.scala
- ingest-check-preservica-for-existing-io/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-upsert-archive-folders/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/testUtils/ExternalServicesTestUtils.scala
- project/Dependencies.scala
This PR:
1. Renames "PartitionKey"
2. Accounts for the fact that the executionId in "message" could be missing
3. Verifies the request sent to the lock table in the tests
> Dr2 1672 add updated partition keys and account for missing execution

- entity-event-generator-lambda/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- get-latest-preservica-version-lambda/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-asset-reconciler/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-find-existing-asset/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-mapper/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-parent-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-start-workflow/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-upsert-archive-folders/src/main/scala/uk/gov/nationalarchives/Lambda.scala
- ingest-workflow-monitor/src/main/scala/uk/gov/nationalarchives/Lambda.scala
These were added so we could deploy without breaking things. The
terraform changes are in so these can be deleted.
> DR2-1702 Remove temporary classes.

- build.sbt
This is a case of removing the override that gave it the old name. This
can't be deployed until
https://github.com/nationalarchives/dr2-terraform-environments/pull/124
is merged and deployed.
> DR2-1716 Update lambda name

- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormatters.scala
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoReadUtils.scala
- dynamo-formatters/src/test/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormattersTest.scala
- ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/XMLCreatorTest.scala
- ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/testUtils/ExternalServicesTestUtils.scala
- ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/ingestassetreconciler/testUtils/ExternalServicesTestUtils.scala
- ingest-find-existing-asset/src/test/scala/uk/gov/nationalarchives/ingestfindexistingasset/testUtils/ExternalServicesTestUtils.scala
- ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/LambdaTest.scala
- ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/XMLCreatorTest.scala
- ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/testUtils/ExternalServicesTestUtils.scala
DR2-1709 Add childCount to Dynamo case classes
This allows us to read the childCount out of Dynamo. The ticket says that this should be on all rows so I've made it mandatory.
> DR2-1709 Add child count to case classes

- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormatters.scala
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoReadUtils.scala
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoWriteUtils.scala
- dynamo-formatters/src/test/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormattersTest.scala
- ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/XMLCreatorTest.scala
- ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestfolderopexcreator/Lambda.scala
- ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/LambdaTest.scala
There's a few changes here.
The DynamoFormatters now add skipIngest to the Asset case classes.
When it's being read, if it's missing, it's false and when it's being
written, if it's false, we don't write it to the table.
This will be rare enough that writing `skipIngest = false` to every
asset row is a bit wasteful.
I've then changed the folder opex creator to filter on skipIngest after
we've done the check on the childCount.
> DR2-1752 Handle skipIngest in folder creator.

- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormatters.scala
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoReadUtils.scala
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoWriteUtils.scala
- dynamo-formatters/src/test/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormattersTest.scala
- ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/XMLCreatorTest.scala
- ingest-files-change-handler/src/main/scala/uk/gov/nationalarchives/ingestfileschangehandler/Lambda.scala
- ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/LambdaTest.scala
- ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/Utils.scala
This will always be empty for now because the judgments don't use it but
it will be useful for TDR transfers.
> DR2-1802 Use correlation id as parent message id.

- ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/DiscoveryService.scala
- ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/Lambda.scala
- ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/MetadataService.scala
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/DiscoveryServiceTest.scala
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/LambdaTest.scala
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/MetadataServiceTest.scala
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/testUtils/LambdaTestTestUtils.scala
- ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/FileProcessor.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/FileProcessorTest.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/LambdaTest.scala
The way this works is roughly
* parsed-court-document-handler adds series to the top level folder.
* ingest-mapper gets all of the top level folders, reads the series,
and creates a de-duped list.
* The department is found with `series.split(" ").head`
* The department and series are found from the discovery API.
* Based on the parent top level folder, the `${department.id}/${series.id} prefix is prepended to the parent path.
* This is written to Dynamo along with the series.
* Everything downstream runs off parentPath so this should just work.
This has not been tested on integration because I can't get into AWS so there may be some small tweaks but this is ready for review.
> DR2-1480 Allow for different departments in the same batch.

- ingest-mapper/README.md
- ingest-parsed-court-document-event-handler/README.md
- ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/Lambda.scala
- ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/SeriesMapper.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/LambdaTest.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/SeriesMapperTest.scala
This is not causing any problems as such but we’re sending
department and series into the step function input and we’re
not using it. It’s safest to take it out so we’re not tempted
to use it and to make sure it’s not being picked up somewhere unexpected.
> DR2-1833 Remove department and series from output/sfn input

- ingest-mapper/README.md
- ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/MetadataService.scala
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/LambdaTest.scala
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/MetadataServiceTest.scala
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/testUtils/LambdaTestTestUtils.scala
- ingest-parsed-court-document-event-handler/README.md
- ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/FileProcessor.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/FileProcessorTest.scala
- ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/LambdaTest.scala
We are getting an error in the ingest mapper when the series is coming back from the document-handler as null.
To fix this, we’re going to stop sending null as the Series. This will allow us to validate the series and stops passing nulls around.
The parsed-court-document-handler will output Unknown with the name as Court Documents (court unknown) if the series is not known.
If the ingest-mapper finds Unknown, it creates the Unknown/Court Documents (court unknown) folder structure.
> DR2-1832 Use unknown when series is null

- scala/lambdas/ingest-files-change-handler/src/main/scala/uk/gov/nationalarchives/ingestfileschangehandler/Lambda.scala
- scala/lambdas/ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/LambdaTest.scala
- scala/lambdas/ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/Lambda.scala
- scala/lambdas/ingest-parsed-court-document-event-handler/src/test/resources/application.conf
- scala/lambdas/ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/LambdaTest.scala
The parsed court document handler was loading its own config rather than
using the config passed to it. I've updated this.
The files change handler is throwing an error if there is an unexpected
number of children. We talked about this a little while ago and this can
be valid. At any rate, these errors are making it difficult to see if
the process is working so I've taken them out.
I've also added a couple of logging lines, I'll remove them later.
> Minor lambda changes.

- python/lambdas/copy-files-from-tdr/lambda_function.py
- python/lambdas/copy-files-from-tdr/lambda_function_test.py
From the AWS docs:
This is a managed transfer which will perform a multipart copy in multiple threads if necessary
I've removed the test which tests for a standard transfer and we've had
to stop counting the parts as it's not consistent.
> Use the boto3 copy method.

- scala/lambdas/preingest-tdr-aggregator/src/main/scala/uk/gov/nationalarchives/preingesttdraggregator/Aggregator.scala
- scala/lambdas/preingest-tdr-aggregator/src/main/scala/uk/gov/nationalarchives/preingesttdraggregator/Duration.scala
- scala/lambdas/preingest-tdr-aggregator/src/main/scala/uk/gov/nationalarchives/preingesttdraggregator/Lambda.scala
- scala/lambdas/preingest-tdr-aggregator/src/test/scala/uk/gov/nationalarchives/preingesttdraggregator/AggregatorTest.scala
The problem we're having is that each fiber was running in parallel and
trying to get the Group from the Map at the same time. Ref allows
parallel access to the Map. All the fibers were finding the Map empty
and starting a new group.
The solution is to use AtomicCell which only allows one thread to access
it at once. To make this work, I've refactored it so the read and write
of the map are inside the same evalMap call on AtomicCell.
> Fix concurrency issues.

- scala/lambdas/ingest-files-change-handler/src/main/scala/uk/gov/nationalarchives/ingestfileschangehandler/Lambda.scala
- scala/lambdas/ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/LambdaTest.scala
We have been getting an error:
`Expected 1 parent asset, found 0 assets for file <id>: java.lang.Exception`
This is most likely because the update to the asset has been processed first and the asset has been deleted.
The solution is just to ignore it if the file has no parent.
This is because if the file has no parent, this means that the parent has already been processed and the ingest complete message sent.
We can’t ever get into a race condition if the asset is complete and the files aren’t because the ingest complete message won’t send for the asset if that’s true and the asset will still be there.
I’ve changed the method which gets the parent asset to return an `Option`. If there isn’t one, it will do nothing.
I've removed the test which checks for this error and I've added one in …
> DR2-1876 missing parent errors.

- scala/lambdas/ingest-files-change-handler/TestCases.md
- scala/lambdas/ingest-files-change-handler/src/main/scala/uk/gov/nationalarchives/ingestfileschangehandler/Lambda.scala
- scala/lambdas/ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/LambdaTest.scala
The problem is with the logic in the change handler and the order we get sent the messages.
Because the custodial-copy process picks up the ingested files before the step function sets ingested_PS to true, we get two updates in this order
```
ingested_PS=false, ingested_CC=true
ingested_PS=true,ingested_CC= true`
```
The logic was:
```scala
if asset.ingestedPreservica && asset.ingestedCustodialCopy then
//send IngestComplete
else if asset.ingestedPreservica && asset.skipIngest then
//Send IngestUpdate with some other logic around assets with the same Id
else if asset.ingestedPreservica then
// Send ingest update message
So it was never hitting the last else if because ingestedPreservica was never true on its own.
```
The solution is to split them:
```scala
if asset.ingestedPreservica then …
```
> DR2-1884 Change handler not sending update message

- python/lambdas/copy-files-from-tdr/copy_files_lambda_function_test.py
- python/lambdas/copy-files-from-tdr/lambda_function.py
- python/lambdas/copy-files-from-tdr/requirements-runtime.txt
We were getting an error
` No module named 'rpds.rpds`
This issue comment
https://github.com/aws/aws-cdk/issues/26300#issuecomment-1629842430
says we need to pin the jsonschema import to that version. This has
stopped the error.
Also, head_object in boto3 needs named arguments and I've updated the
tests to reflect this.
> Minor copy lambda fixes.

- build.sbt
- scala/lambdas/build.sbt
- scala/lambdas/custodial-copy-queue-creator/src/main/scala/uk/gov/nationalarchives/custodialcopyqueuecreator/Lambda.scala
- scala/lambdas/entity-event-generator-lambda/src/main/scala/uk/gov/nationalarchives/entityeventgenerator/Lambda.scala
- scala/lambdas/get-latest-preservica-version-lambda/src/main/scala/uk/gov/nationalarchives/getlatestpreservicaversion/Lambda.scala
- scala/lambdas/ingest-failure-notifications/README.md
- scala/lambdas/ingest-failure-notifications/src/main/resources/application.conf
- scala/lambdas/ingest-failure-notifications/src/main/scala/uk/gov/nationalarchives/ingestfailurenotifications/Lambda.scala
- scala/lambdas/ingest-failure-notifications/src/test/scala/uk/gov/nationalarchives/ingestfailurenotifications/LambdaTest.scala
- scala/lambdas/ingest-failure-notifications/src/test/scala/uk/gov/nationalarchives/ingestfailurenotifications/LambdaTestUtils.scala
- scala/lambdas/ingest-files-change-handler/src/main/scala/uk/gov/nationalarchives/ingestfileschangehandler/Lambda.scala
- scala/lambdas/ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/LambdaTest.scala
- scala/lambdas/ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/Utils.scala
- scala/lambdas/ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/Lambda.scala
- scala/lambdas/preservica-config/src/main/scala/uk/gov/nationalarchives/preservicaconfig/Lambda.scala
- scala/lambdas/utils/src/main/scala/uk/gov/nationalarchives/utils/EventCodecs.scala
- scala/lambdas/utils/src/main/scala/uk/gov/nationalarchives/utils/ExternalUtils.scala
This lambda will be triggered by the step function failure
notifications.
It first gets the groupId and batchId out of the step function input
which is sent as part of the eventbridge rule. This will work for the
preingest and ingest step functions as they both have these in their
input.
It then looks up that group id in the lock table and for each asset it
finds, it will send an update message saying there has been an error.
I also renamed EventDecoders to EventCodecs as it has encoders now as
well and I moved some of the messaging stuff into utils as there's
multiple things using it now.
> DR2-1909 Ingest failure notifications

- .github/workflows/e2e-tests.yml
The default is 1 hour but the e2e tests take so long to run this isn't
enough. We'll try two hours for now and see how that goes.
> Increase role duration.

- scala/lambdas/preingest-tdr-package-builder/src/main/scala/uk/gov/nationalarchives/preingesttdrpackagebuilder/Lambda.scala
- scala/lambdas/preingest-tdr-package-builder/src/test/scala/uk/gov/nationalarchives/preingesttdrpackagebuilder/LambdaTest.scala
We don't want to have the file extension stripped and we want to use the
description from TDR when available
> DR2-2004 Don't strip filenames and use description

- scala/lambdas/preingest-tdr-aggregator/README.md
- scala/lambdas/preingest-tdr-aggregator/src/main/scala/uk/gov/nationalarchives/preingesttdraggregator/Aggregator.scala
- scala/lambdas/preingest-tdr-aggregator/src/main/scala/uk/gov/nationalarchives/preingesttdraggregator/Lambda.scala
- scala/lambdas/preingest-tdr-aggregator/src/test/scala/uk/gov/nationalarchives/preingesttdraggregator/AggregatorTest.scala
- scala/lambdas/preingest-tdr-aggregator/src/test/scala/uk/gov/nationalarchives/preingesttdraggregator/LambdaTest.scala
We need to do this
https://docs.aws.amazon.com/lambda/latest/dg/example_serverless_SQS_Lambda_batch_item_failures_section.html
This catches any execption, turns it into a custom case class with the
messageId from the message and then returns that as the result from the
lambda.
I've added some tests to check that we're returning the correct id.
> DR2-2117 Aggregator to return list of failures.

- scala/lambdas/entity-event-generator-lambda/src/main/scala/uk/gov/nationalarchives/entityeventgenerator/Lambda.scala
- scala/lambdas/entity-event-generator-lambda/src/test/scala/uk/gov/nationalarchives/entityeventgenerator/LambdaSpec.scala
This will now:
* Get the updated since date from Dynamo
* Get entities-updated-since from Preservica for events 10 minutes
before that time.
* Get the event actions for all entities and get the latest action time.
* If the latest time is before the event action time - 10 minutes, send
the message.
> DR2-2130 Only look at events 10 minutes old.

- project/Dependencies.scala
- scala/lambdas/build.sbt
There was an old secrets manager sdk that we're not actually using so
I've removed that.
Also, scanamo is using an old version of the Dynamo library which might
also be a problem so I've overridden that.
> Update vulnerable dependencies.

- scala/lambdas/ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/DiscoveryService.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/DiscoveryServiceTest.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/LambdaTest.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/testUtils/LambdaTestTestUtils.scala
This catches any errors calling the discovery API and returns the same
object we do if Discovery returns nothing.
I've updated the tests to check for this.
> DR2-2147 Ignore Discovery API failures

- scala/lambdas/ingest-failure-notifications/README.md
- scala/lambdas/ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/Lambda.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/LambdaTest.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/testUtils/LambdaTestTestUtils.scala
Because the failure notifications lambda needs the 'groupId', the workflow step function needs it and because the workflow step function needs it, the Mapper should return it so that it is passed along. The Lambda currently bases the groupId on the batchId but this is only until the step function starts passing it in on its own
> Update Mapper Lambda Output with groupId

- scala/lambdas/ingest-asset-reconciler/src/main/scala/uk/gov/nationalarchives/ingestassetreconciler/Lambda.scala
- scala/lambdas/ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/ingestassetreconciler/LambdaTest.scala
We need to add the ioRef to the output so that this is added to the
post-ingest table so that the CC confirmer can look this up in the OCFL
repo without having the confirmer contact Preservica.
> Add io ref to reconciler output.

- .github/dependabot.yml
Dependabot can't find any gradle files. I don't know if this will help
but it's worth a try.
> Change dependabot config

- project/Dependencies.scala
- scala/lambdas/custodial-copy-queue-creator/src/test/scala/uk/gov/nationalarchives/custodialcopyqueuecreator/Utils.scala
- scala/lambdas/entity-event-generator-lambda/README.md
- scala/lambdas/entity-event-generator-lambda/src/main/scala/uk/gov/nationalarchives/entityeventgenerator/Lambda.scala
- scala/lambdas/entity-event-generator-lambda/src/test/scala/uk/gov/nationalarchives/entityeventgenerator/LambdaSpec.scala
- scala/lambdas/entity-event-generator-lambda/src/test/scala/uk/gov/nationalarchives/entityeventgenerator/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/get-latest-preservica-version-lambda/src/test/scala/uk/gov/nationalarchives/getlatestpreservicaversion/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/ingestassetreconciler/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-find-existing-asset/src/test/scala/uk/gov/nationalarchives/ingestfindexistingasset/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/testUtils/ExternalServicesTestUtils.scala
There are two changes here.
We're now returning `hasNext:Boolean` which shows whether there is
another page. If there is, or all messages are deleted, we keep the next
updated time the same and increment the page.
The other change is to return empty list if the last updated date is
after the event time. This is to stop the lambda recursively trying
again until the event date is later as this is a bit of a waste. Now the
lambda will complete and we can try again on the next invocation.
> Entity event generator fixes

- scala/lambdas/ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestassetopexcreator/Lambda.scala
- scala/lambdas/ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestassetopexcreator/XMLCreator.scala
- scala/lambdas/ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/XMLCreatorTest.scala
- scala/lambdas/ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestfolderopexcreator/Lambda.scala
- scala/lambdas/ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestfolderopexcreator/XMLCreator.scala
- scala/lambdas/ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/XMLCreatorTest.scala
- scala/lambdas/ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/LambdaTest.scala
I missed this the first time because we were passing a default string as
open. I've changed the argument to be the security tag type and removed
the default.
> Make Unknown the default.
