nationalarchives/dr2-ingest

- utils/src/main/scala/uk/gov/nationalarchives/EventDecoders.scala
The incoming json has a field Records, not records. This should fix it.
> Fix SQS decoder

- .github/scripts/deploy.py
- ingest-mapper/src/test/scala/uk/gov/nationalarchives/LambdaTest.scala
They're all prefixed with {environment}-dr2- so this should work.
> DR2-1590 Change the workflow to use the new name

- build.sbt
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormatters.scala
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoReadUtils.scala
- dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoWriteUtils.scala
- dynamo-formatters/src/test/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormattersTest.scala
- ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestassetopexcreator/Lambda.scala
- ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestassetopexcreator/XMLCreator.scala
- ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/XMLCreatorTest.scala
- ingest-asset-reconciler/src/main/scala/uk/gov/nationalarchives/ingestassetreconciler/Lambda.scala
- ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/ingestassetreconciler/testUtils/ExternalServicesTestUtils.scala
- ingest-find-existing-asset/src/main/scala/uk/gov/nationalarchives/ingestfindexistingasset/Lambda.scala
- ingest-find-existing-asset/src/test/scala/uk/gov/nationalarchives/ingestfindexistingasset/testUtils/ExternalServicesTestUtils.scala
- ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestfolderopexcreator/Lambda.scala
- ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestfolderopexcreator/XMLCreator.scala
- ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/XMLCreatorTest.scala
- ingest-parsed-court-document-event-handler/src/main/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/Lambda.scala
- ingest-upsert-archive-folders/src/main/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/Lambda.scala
- ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/LambdaTest.scala
- ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/testUtils/ExternalServicesTestUtils.scala
- project/Dependencies.scala
This is now another module in the project.
> DR2-1690 Move Dynamo Formatters

- build.sbt
- project/Dependencies.scala
- rotate-preservation-system-password/src/main/resources/application.conf
- rotate-preservation-system-password/src/main/resources/log4j2.properties
- rotate-preservation-system-password/src/main/scala/uk/gov/nationalarchives/rotatepreservationsystempassword/Lambda.scala
- rotate-preservation-system-password/src/test/scala/uk/gov/nationalarchives/rotatepreservationsystempassword/LambdaTest.scala
This has been tested without the broken Preservica calls and it's
rotating the secret so this is ready for review.
> DR2-1258 Create secret rotation lambda.

- python/lambdas/copy-files-from-tdr/lambda_function.py
- python/lambdas/copy-files-from-tdr/lambda_function_test.py
> Send file Id to aggregator.

- scala/lambdas/ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/MetadataService.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/LambdaTest.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/MetadataServiceTest.scala
The bug is described in the ticket https://national-archives.atlassian.net/browse/DR2-1874
This should fix it. I've updated the metadata test to have multiple
files.
> DR2-1874 Don't duplicate department and series.

- scala/lambdas/ingest-validate-generic-ingest-inputs/src/main/resources/metadata-validation-schemas/asset-validation-schema.json
- scala/lambdas/ingest-validate-generic-ingest-inputs/src/test/scala/uk/gov/nationalarchives/ingestvalidategenericingestinputs/MetadataJsonSchemaValidatorTest.scala
- scala/lambdas/ingest-validate-generic-ingest-inputs/src/test/scala/uk/gov/nationalarchives/ingestvalidategenericingestinputs/testUtils/ExternalServicesTestUtils.scala
> DR2-1919 Add correlationId to schema & refactor 'optional properties'  tests

- scala/lambdas/ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/Lambda.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/LambdaTest.scala
- scala/lambdas/ingest-upsert-archive-folders/src/main/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/Lambda.scala
- scala/lambdas/ingest-upsert-archive-folders/src/test/scala/uk/gov/nationalarchives/ingestupsertarchivefolders/LambdaTest.scala
- **DR2-1907 Remove content assets and content folders from output.**
- **Remove comment**
> DR2 1907 remove content folders assets from output

- scala/lambdas/ingest-asset-opex-creator/src/main/resources/application.conf
- scala/lambdas/ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestassetopexcreator/Lambda.scala
- scala/lambdas/ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/LambdaTest.scala
- scala/lambdas/ingest-folder-opex-creator/src/main/resources/application.conf
- scala/lambdas/ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestfolderopexcreator/Lambda.scala
- scala/lambdas/ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/LambdaTest.scala
- scala/lambdas/ingest-parent-folder-opex-creator/src/main/resources/application.conf
- scala/lambdas/ingest-parent-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestparentfolderopexcreator/Lambda.scala
- scala/lambdas/ingest-parent-folder-opex-creator/src/test/resources/application.conf
- scala/lambdas/ingest-parent-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestparentfolderopexcreator/LambdaTest.scala
- scala/lambdas/utils/src/main/scala/uk/gov/nationalarchives/utils/LambdaRunner.scala
This won't work until Preservica update their bucket policy and I don't
know when  that will be.
> Revert assume role changes.

- scala/e2e-tests/tests/src/test/scala/uk/gov/nationalarchives/e2etests/StepDefs.scala
> Run create files in parallel.

- project/Dependencies.scala
- scala/lambdas/ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-asset-reconciler/src/test/scala/uk/gov/nationalarchives/ingestassetreconciler/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-failure-notifications/src/test/scala/uk/gov/nationalarchives/ingestfailurenotifications/LambdaTestUtils.scala
- scala/lambdas/ingest-files-change-handler/src/test/scala/uk/gov/nationalarchives/ingestfileschangehandler/Utils.scala
- scala/lambdas/ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/ExternalServicesTestUtils.scala
- scala/lambdas/preingest-tdr-package-builder/src/test/scala/uk/gov/nationalarchives/preingesttdrpackagebuilder/TestUtils.scala
There were some version mismatches that were causing the secrets
rotation lambda to fail.
This should fix it.
> Version bumps.

- scala/lambdas/build.sbt
- scala/lambdas/get-latest-preservica-version-lambda/src/main/scala/uk/gov/nationalarchives/getlatestpreservicaversion/Lambda.scala
- scala/lambdas/get-latest-preservica-version-lambda/src/test/scala/uk/gov/nationalarchives/getlatestpreservicaversion/LambdaTest.scala
- scala/lambdas/get-latest-preservica-version-lambda/src/test/scala/uk/gov/nationalarchives/getlatestpreservicaversion/testUtils/ExternalServicesTestUtils.scala
We should be sending slack messages via eventbridge. It's easiest
to just put it in the code.
> DR2-1811 Alert when demo system upgrades

- scala/lambdas/ingest-asset-opex-creator/src/main/resources/application.conf
- scala/lambdas/ingest-asset-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestassetopexcreator/Lambda.scala
- scala/lambdas/ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/LambdaTest.scala
- scala/lambdas/ingest-asset-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestassetopexcreator/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-folder-opex-creator/src/main/resources/application.conf
- scala/lambdas/ingest-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestfolderopexcreator/Lambda.scala
- scala/lambdas/ingest-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestfolderopexcreator/ExternalServicesTestUtils.scala
- scala/lambdas/ingest-parent-folder-opex-creator/src/main/resources/application.conf
- scala/lambdas/ingest-parent-folder-opex-creator/src/main/scala/uk/gov/nationalarchives/ingestparentfolderopexcreator/Lambda.scala
- scala/lambdas/ingest-parent-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestparentfolderopexcreator/LambdaTest.scala
- scala/lambdas/ingest-parent-folder-opex-creator/src/test/scala/uk/gov/nationalarchives/ingestparentfolderopexcreator/testUtils/ExternalServicesTestUtils.scala
- scala/lambdas/utils/src/main/scala/uk/gov/nationalarchives/utils/LambdaRunner.scala
This is so we can get rid of datasync
> DR2-1951 Opex creators assume role and write to bucket directly.

- README.md
- project/Dependencies.scala
- scala/e2e-tests/spec/src/test/scala/uk/gov/nationalarchives/e2etests/E2ESpecUtils.scala
- scala/lambdas/build.sbt
- scala/lambdas/dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormatters.scala
- scala/lambdas/dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoReadUtils.scala
- scala/lambdas/dynamo-formatters/src/main/scala/uk/gov/nationalarchives/dynamoformatters/DynamoWriteUtils.scala
- scala/lambdas/dynamo-formatters/src/test/scala/uk/gov/nationalarchives/dynamoformatters/DynamoFormattersTest.scala
- scala/lambdas/ingest-flow-control/README.md
- scala/lambdas/ingest-flow-control/src/main/resources/log4j2.properties
- scala/lambdas/ingest-flow-control/src/main/scala/uk/gov/nationalarchives/ingestflowcontrol/Lambda.scala
- scala/lambdas/ingest-flow-control/src/test/scala/uk/gov/nationalarchives/ingestflowcontrol/Helpers.scala
- scala/lambdas/ingest-flow-control/src/test/scala/uk/gov/nationalarchives/ingestflowcontrol/LambdaTest.scala
- scala/lambdas/ingest-parsed-court-document-event-handler/src/test/scala/uk/gov/nationalarchives/ingestparsedcourtdocumenteventhandler/TestUtils.scala
- scala/lambdas/preingest-tdr-aggregator/src/test/scala/uk/gov/nationalarchives/preingesttdraggregator/AggregatorTest.scala
Changes in tests, added logging
> Temp branch for flow control

- scala/lambdas/entity-event-generator-lambda/src/main/scala/uk/gov/nationalarchives/entityeventgenerator/Lambda.scala
- scala/lambdas/entity-event-generator-lambda/src/test/scala/uk/gov/nationalarchives/entityeventgenerator/LambdaSpec.scala
Reverts nationalarchives/dr2-ingest#441
> Revert "DR2-2130 Only look at events 10 minutes old."

- scala/lambdas/ingest-mapper/README.md
- scala/lambdas/ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/DiscoveryService.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/DiscoveryServiceTest.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/MetadataServiceTest.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/testUtils/LambdaTestTestUtils.scala
We're now not writing title to Dynamo if the title is missing.
> Make title an option

- python/lambdas/copy-files-from-tdr/lambda_function.py
This makes it easier fo the e2e tests to find errors and it should give
us something to search for in Cloudwatch as well.
This is a quick fix to get the tests working. A better logging solution will be implemented later
> Add json output on error.

- scala/lambdas/build.sbt
- scala/lambdas/ingest-flow-control/src/main/scala/uk/gov/nationalarchives/ingestflowcontrol/Lambda.scala
- scala/lambdas/ingest-flow-control/src/test/scala/uk/gov/nationalarchives/ingestflowcontrol/Helpers.scala
Changed to include execution starter and success sender in the task output
> Dr2 2096 add execution name to task output

- scala/lambdas/ingest-mapper/src/main/scala/uk/gov/nationalarchives/ingestmapper/Lambda.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/MetadataServiceTest.scala
- scala/lambdas/ingest-mapper/src/test/scala/uk/gov/nationalarchives/ingestmapper/testUtils/LambdaTestTestUtils.scala
This is reliant on this [Terraform Environments PR](https://github.com/nationalarchives/dr2-terraform-environments/pull/242) being merged first
> Add 'groupId' to the Input

- .github/workflows/test.yml
- project/Dependencies.scala
There are two steps.
1. Use sbt-dependency-submission to create the dependency graph
2. Use dependency-review-action to scan for vulnerabilities
I've replaced the dr2-github-actions workflow as this is the only project still using it.
> Use dependency review action

- build.sbt
- scala/lambdas/build.sbt
- scala/lambdas/postingest-state-change-handler/src/main/scala/uk/gov/nationalarchives/postingeststatechangehandler/Lambda.scala
- scala/lambdas/postingest-state-change-handler/src/test/scala/uk/gov/nationalarchives/postingeststatechangehandler/LambdaTest.scala
- scala/lambdas/utils/src/main/scala/uk/gov/nationalarchives/utils/ExternalUtils.scala
Filtered out the `REMOVE` event from the decoder.
> Dr2 2366 json parsing errors in postingest change handler
